### ISSUE TITLE
The website is broken?

### ISSUE THREAD

**Issue by Zachiah** [hylo-lang/val#858]
![image](https://github.com/hylo-lang/val/assets/50641830/753b6ff2-af7c-4817-ab2b-b1223b29f400)
https://www.val-lang.dev/

**Comment by kyouko-taiga** [comment]
In the process of renaming. New URL is hypo-lang.org.

**Comment by Zachiah** [comment]
Oh, OK. Thanks!

**Comment by Zachiah** [comment]
Can I make a PR to update the README?

**Comment by kyouko-taiga** [comment]
Sure
